fdcl-nrf/fym

fym/utils/plotting.py
Plotting module 에서 각도 변수 관련 time series 출력 시 label 이 추가되지 않는 오류를 수정하였음
Fix the bug of plotting module when plotting time histories of angular
variables (there were no labels on figures about angular variables).
Corresponding issue: #22
=> Plotting module 레이블 오류 및 한 번에 여러 figure 창을 띄우도록 수정함(#22)

fym/agents/PID.py, fym/envs/quadrotor_hovering.py, fym/models/missile.py, fym/models/quadrotor.py, fym/utils/plotting.py, main_test_PID.py
PID 모듈의 유효성을 판단하기 위해 쿼드로터의 inner-loop 에 해당하는 자세 및 고도제어를 수행함.
1. 수정 내용
- 테스트를 위해 `quadrotor_hovering.py` env 작성 (테스트를 위해 간단히 작성되었으므로 사용 시 주의가 요구됨)
- `PID.py` agent 의 수정이 다소 있음
- 테스트를 위해 `main_test_PID.py` main 코드를 작성 및 PID 모듈 검증
2. 결과
자세한 내용은 아래 commit message 참고.
In order to check PID module, env and test main files of quadrotor are
added in advance.
1. How did I perform this test?
Under small angle assumptions, I assumed that each roll, pitch, and
height channel can be decoupled and controlled by 1) f2 - f4 (torque),
2) f3 - f1 (torque), and 3) total thrust, respectively. So I designed
simple PID controllers for each channel independently. In addition, to
resolve the redundant DoF of one, an additional condition was added.
2. To reviewers
Plz check my codes and correct them if there …
=> PID 모듈 확인 (#50)

README.md, setup.py
Python `setup` 모듈을 이용해서 설치가 가능하게 만들었습니다.
사용법은 `pip install -e .` 로 설치파면 되고 여기서 `-e` 옵션때문에 패키지 내용에 업데이트가 있어도 바로 설치된 `fym` 모듈에 바로 반영이 됩니다. (README.md) 에 반영함)
- 이제 `if __name__ == '__main__':` 이 구문이 들어간 모듈 파일이 프로젝트 루트 디렉터리에서 바로 실행 가능합니다.
(예: `python fym/models/quadrotor.py`)
=> pip를 이용해 fym 모듈 설치가 가능하게 만들었습니다. (#73)

fym/utils/linearization.py
예전엔 함수의 input order가 어느정도 정해져 있어야 했다.(첫 번째 input은 무조건 state여야 했으며 control, external, time등이 오면 셋 중엔 control이 무조건 먼저 와야 했다.)
이젠 function의 input arguments 순서를 자유롭게 만들어도 되며 선형화할 때 function의 몇 번째 argument로 자코비안을 구할 것인지 정해주면 된다.
before
Function which user wants to linearize have to observe the order of
input arguments.
after
The function have not to observe the order of input arguments.
User just determine which numberth of input arguments the function
should be linearized about
=> 선형과 모듈 개선(#67)

fym/agents/PID.py
Fix default assigned value  bug (#50)
Currently, PID module receives the values of windup function, i.e. the
maximum allowable values. However, the default value of windup is
assigned as 'True', which is not applicable for the current code.
Therefore, the default value is changed as 'False'. Note that 'False',
the boolean is valid as an exception, whereas 'True' is invalid.
=> PID 모듈 windup 기본값 버그 수정 (#50)

fym/core.py
core.py 의 전반적인 개선을 했습니다.
- 이제 `observation_space` 를 `systems`의 초기값으로부터 자동으로 추측하게 할 수 있습니다.
- `BaseEnv.__init__`의 불필요한 `obs_space`, `action_space` 인자들을 제거했습니다,
- 적분이 이제 `scipy`의 포트란 코드로 동작합니다 (간단한 실험결과 2배 이상 속도 향상, #84 )
- `Clock` 클래스를 만들어 여러 루프의 시뮬레이션 관리가 수월해졌습니다.
- `BaseSystem.deriv` 대신 `BaseEnv.derivs`로 여러 시스템들 간의 상호작용 코드를 짜기 편해졌습니다.
- Infer the `observation_space` based on `systems`.
- Remove the `obs_space` and `obs_space` arguments in `__init__` method,
and replace it with attribute checking statements.
- Integration improved. Now the integrator uses
`scipy.integrate.odeint` (#84).
- Add Clock class which helps us manage the iteration time, episode
number, etc, more intuitively and clearly.
- Remove the need of `BaseSystem.deriv` and replace it with
`BaseEnv.derivs`. This is more …
=> Improve core

fym/core.py, fym/utils/logger.py
데이터 로거 모듈을 만들었습니다. (관련 이슈: #53, #45)
- 이제 `BaseEnv` 가 자동으로 state 히스토리를 log 파일에 저장합니다. (기본값: `log/<yyyymmdd-hhmmss>/state_history.h5`)
- 로거는 기본적으로 내부 버퍼에 딕셔너리 형태로 로깅을 합니다. (`Logger.log_dict` 메서드 이용)
- 내부 버퍼 크기가 `Logger.max_len`에 도달하면 log 파일에 append 하고 내부 버퍼를 비웁니다.
- 이 로거는 `BaseEnv` 뿐만 아니라 다른 외부 환경에서도 이용가능합니다.
- Related issues: #53, #45
- Now a BaseEnv logs the internal state history automatically to a
log directory (default: `log/<yyyymmdd-hhmmss>/state_history.h5`)
- The logger store dictionary-like values in the local buffer, and
whenever the buffer length get bigger than a `max_len`, the data is
dumped (appended) to the hdf5 file.
=> Create a data logger

fym/core.py, test/figures.py, test/performance_compare.py, test/validation.py
v0.4 의 첫번째 풀리퀘입니다.
적분 속도향상을 위해 전반적인 메커니즘과 API 를 수정했습니다.
사용 예제는 `test/performance_compare.py` 를 보시면 됩니다.
- `BaseEnv`는 이제 `dict` 를 state 로 들고다니지 않습니다. 대신 각 state 들은 `ndarray` 타입으로 각 `BaseSystem` 에 저장되고, 매 적분시 업데이트 됩니다. 이 방식으로 인해 굳이 다시 `dict` 로 pack / unpack 하는 불필요한 과정이 줄어 적분속도가 7배 향상되었습니다.
- `BaseEnv.reset` 메소드는 이제 아무 값도 리턴하지 않습니다. 대신 `BaseEnv` 내의 등록된 모든 `BaseSystem` 들의 state 를 `BaseSystem.initial_state` 로 업데이트 합니다. 따라서 RL을 위해 `reset` 을 새로 정의해야 합니다. 이는 `BaseEnv` 를 기반으로 사용자가 직접 `Env`를 구성할 때 기본적으로 고려해야할 사항이기 때문입니다.
- `Env` 구성시 `observation`을 직접 지정해 주어야 합니다. 기본적으로 현재 각 `BaseSystem`들의 상태를 모아서 리턴하면 됩니다. 이를 편리하게 하기 위해 기본적으로 `BaseEnv.observe_dict` 와 `BaseEnv.observe_flat` 메소드를 제공합니다.
- `BaseEnv.step` 메소드는 RL 환경 구성 시, reward 나 terminate 조건을 설정하는데 필요하기 때문에 사용자가 직접 구성하여야 하는데, 이전보다 훨씬 간단해졌습니다. 단순히 …
=> Improve speed

fym/core.py, test/delay_test.py
각 상태변수 (states) 신호에 고정 시간 딜레이를 주는 기능을 만들었습니다.
딜레이 신호를 얻고 싶은 시스템을 특정 지을 수 있어 효율적입니다.
간단하게 `Env.__init__` 메소드에서 `super().__init__(**kwargs)` 라인 이후에 다음을 호출하여 사용합니다.
```python
self.set_delay([systems], T)
```
이 라인을 호출하면 `self` (`Env()`) 에 `delay` 인스턴스가 생성되며 `Env` 내의 어디서든 다음 구문을 통해 
각 시스템에 딜레이 된 신호를 저장할 수 있습니다. 저장된 딜레이 신호는 `system.d_state` 로 접근 가능합니다.
```python
if self.delay.available():
self.delay.set_states(time)
delayed_main_state = self.systems["main"].d_state
```
=> Add a delay function to core

fym/plotting.py, test/plot_figures.py
- `plotting.py` 에 그래프의 type 을 지정할 수 있는 기능을 추가하였습니다.
`plot_type` 은 기본값으로 `plot` 을 가지며, 현재 `plot`, `step` 두 속성을 가질 수 있습니다.
- `set_plot_type` 메쏘드를 이용하여 `step` 형태의 그래프를 그리도록 class instance 의 속성을 변경할 수 있습니다.
예: `test/plot_figures.py` 내의 코드 중 일부:
```python3
plotter.plot2d(time, ctrl, name='ctrl', xlabel='t (s)', ylabels=['$L (g)$', '$\phi (deg)$'])
plotter.set_plot_type("step")
plotter.plot2d(time, ctrl, name='ctrl', xlabel='t (s)', ylabels=['$L (g)$', '$\phi (deg)$'])
```
결과 비교:
- `plot_type = plot` 을 이용한 경우: ![image](https://user-images.githubusercontent.com/43136096/73429441-0b6fb800-437f-11ea-914d-81cc3612df96.png)
- `plot_type = step` 을 이용한 경우: ![image](https://user-images.githubusercontent.com/43136096/73429450-132f5c80-437f-11ea-96ec-97e500749b44.png)
=> [plotting module] plot type 지정 기능 추가

fym/core.py, fym/logging.py, test/group_test.py
- `__repr__` 메소드를 좀 더 보기 쉽게 만들었습니다
- `render` 메소드를 사용시, `env` 가 `reset` 되며 `tqdm` 도 다시 시작하도록 바꿨습니다.
- `fym.logging` 모듈에 `h5py` 파일 포인터를 만들 때 `mode`를 지정할 수 있게 바꿨습니다. 이제 `mode=a` 옵션을 주면 파일을 새로 만들거나 기존 파일에 이어서 저장할 수 있습니다.
- `BaseEnv`에서 `odeint` 사용시 `odeint_option` 으로 적분 설정값을 넣어줄 수 있게 바꿨습니다.
- `test/group_test.py` 를 조금 수정했습니다.
=> Improve fym

fym/logging.py
logger 에 info 데이터를 추가하는 기능을 만들었습니다.
`logger.set_info` 메소드를 사용하며, 중복 호출될 경우 같은 이름의 데이터는 덮어씌워 집니다.
다음과 같이 사용 가능합니다.
```python
import fym.logging as logging
logger = logging.Logger(path="test.h5")
logger.record(time=0, state=[1, 2, 3], control=0)
logger.record(time=1, state=[2, 3, 4], control=0.1)
logger.record(time=2, state=[0, 0, 0], control=0.3)
logger.set_info(name={"first": "Name", "second": "SecondName"}, number=6)
logger.set_info(name={"first": "ChangedName"}, newnumber=10)
logger.close()
data, info = logging.load("test.h5", with_info=True)
print(data, info)
```
=> Improve logger

fym/core.py
`BaseSystem`을 조금 더 간단하게 선언할 수 있도록 바꿨습니다.
예시:
```python
a = BaseSystem()  # 초기 상태: zeros(1, 1) 
a = BaseSystem(shape=(2, 3))  # 초기 상태: zeros(2, 3)
a = BaseSystem([1, 2])  # 이전과 같음
```
=> BaseSystem improve

fym/plotting.py, test/plot_figures.py
- 새로운 plot module 을 추가.
- 사용법은 `test/plot_figures.py` 와 같이, "데이터를 담은" 딕셔너리 (`fym.logging` 에서 불러와진 것을 전제로 함) 와 "plot 정보를 담은" 딕셔너리를 이용함.
- 코드 예시는 `test/.` 에서 `python plot_figures.py` 를 실행하여 확인 가능
- 코드 예시
```python3
import os
import numpy as np
import matplotlib.pyplot as plt
import fym
import fym.plotting as plotting
import fym.logging
data = fym.logging.load('data/plot_figures/result.h5')  # a simulation result obtained from fym
state = data['state']
ctrl = data['control']
time = data['time']
plotter = plotting.Plotter()
plotter.plot2d(time, state)  # tmp
data_dict = data
data_dict["state3d"] = data["state"][:, :3]  # for 3d example
data_dict["control_shift"] = data["control"] + np.rad2deg(1)  # broadcasting; for 2d example
draw_dict = {
"state_012": {
"plot": ["state3d"],
"type": "3d", …
```
=> Add a new plotting module

fym/plotting.py, test/plot_figures.py
- 3차원 그래프의 axis equal 기능 추가
- `test/plot_figures.py` 실행 시 결과 비교
1. axis equal 적용 안함
2. 적용 시
- `pyplot` 에서 기본적으로 3차원 그래프의 axis equal 기능을 지원하지 않음... 2차원 그래프의 경우 `ax.axis("equal")` 로 가능하나, 3차원은 아래와 같은 오류 메시지가 나타남:
- 해결 방법은 [Stack Overflow 답변](https://stackoverflow.com/questions/13685386/matplotlib-equal-unit-length-with-equal-aspect-ratio-z-axis-is-not-equal-to) 을 참고함
=> Add axis equal for 3d plot

fym/core.py, fym/models/aircraft.py
core.py:
- Comment out an unnecessary initial state initialization
aircrafy.py:
- Set default state to a trim when there is no input argumnet.
- Fix _get_trim return value to float
=> Fix little glitches

fym/utils/parser.py, test/parser/agent.py, test/parser/main.py
---
This module assists setting up the configuration of each module and scripts. It parses JSON files with dot notation such as `settings.json` in [Visual Studio Code](https://code.visualstudio.com).
`fym.utils.parser.parse` parses a JSON-like `dict` object to a nested [`types.SimpleNamespace`](https://docs.python.org/3/library/types.html#types.SimpleNamespace) object like following. It encodes a dotted key into a nested structure to make ease of grouping the configuration.
```python
import fym.utils.parser as parser
from fym.core import BaseEnv, BaseSystem
json_dict = {
"env.kwargs": dict(dt=0.01, max_t=10),
"multicopter.nrotor": 6,
"multicopter.m": 3.,
"multicopter.LQRGain": {
"Q": [1, 1, 1, 1],
"R": [1, 1],
},
"actuator.tau": 1e-1,
}
cfg = parser.parse(json_dict)
```
Because the …
=> Add a parser module

fym/__init__.py
List of directly callble modules/classes/methods:
```python
fym.BaseEnv  # fym.utils.BaseEnv
fym.BaseSystem  # fym.utils.BaseSystem
fym.parser  # fym.utils.parser
fym.jacob_analytic  # fym.utils.linearization.jacob_analytic
fym.jacob_numerical  # fym.utils.linearization.jacob_numerical
fym.load  # fym.logging.load
fym.Logger  # fym.logging.Logger
fym.clqr  # fym.agents.LQR.clqr
fym.dlqr  # fym.agents.LQR.dlqr
```
=> Make some module called directly

fym/core.py, fym/logging.py
Inner ``Logger``s was designed to record inner data of ``BaseEnv``, so attempts to directly record any data to the inner logger should be blocked.
I've made a method ``Logger._record`` that works the same as the previous ``Logger.record`` method, and add a line to check the ``Logger`` is inner or not inside the previous ``Logger.record`` method for compatibility.
This resolves #179 .
=> Block direct call of `Logger.record` method of inner Logger

fym/core.py
* state attributes are now copied when they are called with `observe_*` methods.
* Inner logger is now checked with, e.g., `logger is not None`.
=> Copy states in observe_* methods
