fdcl-nrf/fym

fym/agents/PID.py
fym/envs/quadrotor_hovering.py
main_test_PID.py

Feature/iss50 skim review 의 리뷰 내용을 테스트하고 반영하였습니다.
관련 이슈: #50

리뷰 내용 반영 Feature/iss50 skim review (#50)

---

fym/envs/two_wheels_robot_pathplanning.py
fym/models/two_wheels_robot.py

Change two wheel robot model.
before
state : [x position, y position, x velocity, y velocity,
theta(attitude)]
after
state : [x position, y position, speed, theta(attitude)]
Also, two wheel robot pathplanning env is changed according to two wheel
robot model's change.
before
state's lb and ub had five elements
after
state's lb and ub have four elements

two wheel robot 모델과 env 변경(#80)

---

MANIFEST.in
setup.py

Commits in this pull request include several improvements of `setup.py` and the package structure.

Make the package installable from PyPI

---

fym/core.py
test/group_test.py

한 env 내에 여러 시스템을 넣을 수 있되, 각 시스템의 변수명을 적절히 정의하고 가지고 다닐 수 있게 만들었습니다.
이렇게 하면 고정익 항공기처럼 13개 가량의 많은 상태변수를 가지는 시스템을 구성할 때, 하나하나 인덱싱을 하지 않고도 위치나 자세 등 의미를 가지는 상태변수들을 사용하여 동역학 방정식을 쉽게 구성할 수 있습니다.
즉, 다음과 같은 코드 구현이 가능합니다.
```
Env
"Aircraft-1"
"position" (3,)
"velocity" (3,)
"quaternion" (4,)
"angular-velocity": (3,)
"Aircraft-2"
"polar" (2,)
"Adaptive-controller" (18,3)
```

Add base group

---

fym/models/aircraft.py
fym/utils/rot.py

종방향 모핑항공기 모델입니다. 13차원 비선형 모델이며, 공력해석 프로그램에서 구한 공력을 2차 다항식으로 근사화 해서 빠른 계산을 수행할 수 있도록 구성하였습니다.
#125 를 사용해서 각 상태변수들을 내부 시스템으로 가지고 다닙니다.
상태변수는 순서대로 `velocity (3), omega (3), quaternion (4), position (3)` 이며
입력은 조종면 입력 (4) `thrust, elevator, aileron, rudder` 와 모핑형상 입력 (2) `eta1, eta2` 입니다.
트림점은 `get_trim` 메소드로 얻을 수 있으며 고도, 속력, 모핑형상을 고정시킨 상태에서 받음각, 추력, 엘리베이터를 최적화합니다.

Add a morphing aircraft

---

fym/core.py

- forked repo 에서 PR 을 보내기 위해서 이전 PR #127 을 닫고 다시 연 PR 임.
===========================================================
- `core.py` 에 `deriv` method 가 필요없어져서 삭제함
- #125

Comment on pr #125

---

fym/core.py

RK4를 `solver` 옵션으로 추가할 수 있게 만들었습니다.

Add an RK4 as an option for the solver

---

fym/core.py
fym/logging.py
fym/models/aircraft.py

Huge update

---

fym/utils/rot.py

Improve rotation module

---

fym/models/aircraft.py
fym/utils/rot.py

f16 longitudinal model을 fym에 추가했습니다.

Add f16 lon

---

fym/models/aircraft.py

Modify fym/models/aircraft.py

---

fym/models/aircraft.py

- `F16LinearLateral` 모델을 책에서 단위나 변수명을 찾아보기 힘들어서 설명을 추가하였습니다.
특히 단위가 rad, deg 를 섞어 쓰니 주의바랍니다.
- washout filter variable 이 뭔지 잘 모르겠는데, 필요 없으면 마지막 변수만 날리고 쓰면 됨

[Model] F16LinearLateral 모델 설명 추가

---

fym/plotting.py
test/plot_figures.py

- 색상 속성을 "color" 에서 "c" 로 변경 (`Matplotlib.pyplot.plot`와 일치)
- 일반적인 기타 `Matplotlib.pyplot.plot` 속성을 건드릴 수 있게 dictionary key 로 받도록 변경
- 변경사항을 안 넣었었네요 죄송 ㅎ

Add small change (plotting module)

---

fym/utils/rot.py

I created a `dcm2angle` function in `utils/rot.py` at @JungYT's request.
This resolves PRs #99 #161.

Add a dcm2angle function

---

fym/models/quadrotor.py

Add a Multirotor class

---

LICENSE
fym/agents/LQR.py
fym/core.py
fym/envs/cmrac.py
fym/envs/dynamic_soaring.py
fym/envs/quadrotor_hovering.py
fym/envs/stationary_target_interception.py
fym/envs/two_wheels_robot_pathplanning.py
fym/models/aircraft.py
fym/models/missile.py
fym/models/quadrotor.py
fym/models/two_wheels_robot.py
setup.py

- Remove unnecessary dependencies of `gym`
- Change the outputs of LQR module
- Add a `dcm2angle` function in `utils.rot` module
- Add a `Multirotor` class
- Add a `LINCENSE` file

Version 1.1.3

---

fym/core.py
fym/utils/rot.py

Resolve #166.
자세 표현하는게 자주 헷갈려서 변수에 대한 설명 및 동역학을 docstring에 적어보았습니다.
@seong-hun 제가 docstring 을 자주 안 써봐서, 혹시 convention 과 다르다면 리뷰 부탁드립니다 ㅎ

Add docs for `fym/utils/rot.py`

---

fym/core.py

See the [full documentation](https://www.notion.so/nrfteams/Logger-64a200bfc2784df3b0eaef1891131990).
There are several way to save a experimental data in `fym`.
Sometimes, the data users want to record can be simply state variables within the `BaseEnv` and/or `BaseSystem` and data derived from them (i.e. control inputs). When using `fym`, there is one major `BaseEnv` that runs the simulation with `BaseEnv.update` method. The `BaseEnv.logger_callback` method defines information to be recorded in every time step when the environment updates. See the example below.
```python
from fym.core import BaseEnv, BaseSystem
import fym.logging
class Env(BaseEnv):
def __init__(self):
super().__init__(dt=0.01, max_t=10)
self.plant = BaseSystem([[1], [1]])
self.actuator = BaseSystem()
self.controller = …
```

Change the logger_callback feature

---

fym/core.py
test/speed-test/baseline.py
test/speed-test/main.py
test/speed-test/usingfym.py

Fym is now more faster than before by using a single pre-allocated state vector that is shared with all the children (`BaseEnv`'s and `BaseSystem`'s).

Make Fym faster

---

fym/logging.py
fym/utils/parser.py
test/speed-test/usingfym.py

`logging` 모듈에서 미리 np.array를 할당하여, recording 속도를 조금 향상 시켰습니다.
사용하는데 있어서 달라진 점은 없습니다.

Improve logging speed

---

fym/core.py

Inner logger behavior is changed.
* `set_dot` has returned value + `logger_callback` method is defined: record both (priority check: `update(set_dot, logger_callback)`)
* `set_dot` doesn't have returned value + `logger_callback` method is defined: record `logger_callback`
* `set_dot` has returned value + `logger_callback` method is not defined: record `set_dot`
* `set_dot` doesn't have returned value + `logger_callback` method is not defined: record `t` and `**observe_dict()`

Improve logging
